### ISSUE TITLE
Interpolate complex data

### ISSUE THREAD

**Issue by fmeirinhos** [IgorKohan/NormalHermiteSplines.jl#1]
Thank you for developing this library!

Currently the interpolation only supports `nodes` with the same type as the function `values`.
Will it be possible for the function `values` to be `Complex` or is it simply better to decompose the spline into sum of real and imaginary valued splines?

**Comment by IgorKohan** [comment]
Hello,
the function values are assumed to be real values, so it is necessary to decompose the spline into sum of real and imaginary valued splines. It is enough to make the  problem Gram matrix factorization just ones and build two splines then. Something like following:
_spline = prepare(nodes)                       # default RK_H0() kernel
re_spline = construct(_spline, re_u)
im_spline = construct(_spline, im_u)
re_result = evaluate(re_spline, points)
im_result = evaluate(im_spline, points)

**Comment by IgorKohan** [comment]
.
